name: flutter_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.3.5
  intl: ^0.20.1
  logging: ^1.2.0
  flutter_datetime_picker_plus: ^2.1.0
  image_picker: ^1.0.7
  image_cropper: ^8.1.0
  video_player: ^2.9.2
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  card_swiper: ^3.0.1
  url_launcher: ^6.3.1
  hyperkyc_flutter: ^0.33.0
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  super_tooltip: ^2.0.9
  flutter_card_swiper: ^7.0.2
  swipe_cards: ^2.0.0+1
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  geolocator: ^13.0.2
  fluttertoast: ^8.2.10
  dotted_border: ^2.1.0
  camera: ^0.11.1
  share_plus: ^10.1.4
  

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Dark mode assets
    - assets/dark/
    - assets/dark/bgs/
    
    # temp images
    - assets/images/
    - assets/icons/
    
    # Light mode assets
    - assets/light/
    - assets/light/bgs/
    
    # Temporary images
    - assets/tempImages/
    
    # Video assets
    - assets/video/Intro_video.mp4
    


  fonts:
    - family: CustomFont  # Replace with your actual font family name
      fonts:
        - asset: assets/fonts/Sukar-Regular.ttf
        - asset: assets/fonts/Sukar-Bold.ttf
          weight: 700
